version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test || true
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS \
            "rm -rf ~/DevOpsProject && \
             git clone https://github.com/cem1000/DevOpsProject.git && \
             cd ~/DevOpsProject && \
             bash ./deploy.sh"
workflows:
  build-and-test:
    jobs:
      - test-node
      - deploy:
          requires:
            - test-node
          filters:
            branches:
              only: main
